### ISSUE TITLE
Feature Request: Implement delete from symstore

### ISSUE THREAD

**Issue by mihai-unity** [elmirjagudin/symstore#14]
First of all, thanks for this great package that we're using and it works great.

What we're missing though is a delete functionality that's well integrated into the package and knows how to properly add the transaction in the history files and remove the required files as described here https://docs.microsoft.com/en-us/windows/win32/debug/using-symstore#transaction-examples

We'd like to use this in a cronjob that should delete everything that is older than a certain date so we can properly optimize the space usage.

**Comment by elmirjagudin** [comment]
Happy to hear that's used at Unity. I'm in the middle of my vacation right now, but I hope I can look into adding delete functionality in a couple of weeks.

**Comment by mihai-unity** [comment]
That'd be great. I looked a little bit into it and it's not trivial in the current architecture even though it looked deceptively easy at first. Maybe you know how to tackle this better.

**Comment by elmirjagudin** [comment]
Hi @mihai-unity 

I implemented an initial version delete operation on the https://github.com/elmirjagudin/symstore/tree/delete branch.

I still need do more work before it's ready to be included into a release. However, if would be nice if you could test what I got so far. So we can catch potential problems early.

On the delete branch, there is an '--delete <transaction_id>' command line option, which will delete the specified transaction from the symstore. Give it a try, if you have an opportunity.

**Comment by mihai-unity** [comment]
Hey,

Unfortunately we have just decided to stop using the symbol server entirely
for other reasons unrelated to this issue. Priorities have changed.

But I appreciate though your time and effort figuring this out but I'll see
if and when I can get the server back up.

Thanks again for your help,
Mihai

**Comment by elmirjagudin** [comment]
No problem Mihai, the constant shifting ground is the name of the game :)

I'll finish up the work on delete feature, and it it all pans out it will be included into the next release.

**Comment by elmirjagudin** [comment]
Delete operation implementation is now merged to master, https://github.com/elmirjagudin/symstore/commit/806093938e513dc2c852559becba55cbfbd90ddd

This new feature will be included into next release, version 0.3.0.
