### ISSUE TITLE
It is not able to take a folder as input and detect pdbs dlls and exes on its own.

### ISSUE THREAD

**Issue by MB23** [elmirjagudin/symstore#15]
It is not able to take a folder as input and detect pdbs dlls and exes on its own. Providing a list of say 1000 files that needs indexing through individual file name is not possible.

**Comment by MB23** [comment]
symstore.exe recursively traverses the folder and subfolders and finds all symbols and indexes them.

**Comment by elmirjagudin** [comment]
The design of this symstore tool is to use shell features to specify what files should be published. For example:

  **symstore my_store src_dir/*.pdb**

would publish all PDB files in the 'src_dir'. If you want to publish all pdb/dll/exe files from a deeply nested directories tree, you can for example use:

  **symstore my_store $(find src_dir -type f -name '*.dll' -o -type f -name '*.pdb' -o -type f -name '*.exe')**

This fill find all PDB/DLL/EXE files in src_dir and all of it's subdirectories and publish them.

Theoretically speaking, if you are publishing 1000s of files, you can run into some limitation in the argument length with the shell or something. However, I have tested publishing ~2600 files in a single transaction, using the above approach, and it worked without any issues for me. So, publishing a couple of thousand files is possible.

Do you have problem publishing a large number of files? What kind of issues are you running into?
