### ISSUE TITLE
Compression on FreeBSD

### ISSUE THREAD

**Issue by shryshuk** [elmirjagudin/symstore#3]
Hi guys,

Would like to run package on **FreeBSD**.
How to install required packages for compression, to get it working?

- gir1.2-libgcab-1.0
- python-gi

Neither #pip nor #pkg knows about these packages.

**Comment by rasjani** [comment]
I've never used  any bsd's so im i can't point  you to straight forward solution but i can give you pointers..

python-gi is essentially a "Python GObject-Introspection" package. It might be found in some repos under names "PyGi" or "PyGObject" or some permutations of that..  Gir then refers to a repository that maintains these introspection (c <-> python code) interfaces. 100% that pip repo doesn't have gir stuff atleast. So, from this point and unless you find some gtk repository for freebsd that might have these, your best option is to compile them yourself ..

**Comment by elmirjagudin** [comment]
Hi @shryshuk,

I'm not an FreeBSD expert but I managed to get compression going by installing gcab and py27-gobject3 packages with 'pkg' command.

E.g. I run commands

```
pkg install gcab
pkg install py27-gobject3
```

However, this only make compression work with python2. I'll see if I can figure out how to get it going with python3...

This is on FreeBSD 11.0 btw.

**Comment by elmirjagudin** [comment]
Added info on required packages on FreeBSD 12.2 to enable compression,

see commit https://github.com/elmirjagudin/symstore/commit/61800b8444f2375a4a23762c69882abdf00d7cd1
