### ISSUE TITLE
long root stream not supported

### ISSUE THREAD

**Issue by cinatic** [elmirjagudin/symstore#5]
Hello,

first thanks for this module, it's awesome.

I tried to add some large pdb files but i get assert "long root stream not supported", was this not added in 2.1?

"support publishing PDBs with multi-page root stream (larger files)"

num_pages*4 = 792 < Page Size 512

**Comment by cinatic** [comment]
it's strange because some files with greater size are working

**Comment by elmirjagudin** [comment]
The pdb parser is really simple, so you probably found yet another style of pdb file it can't handle.

Can you share the file that is giving you problem? I'll try to look into  it.

**Comment by cinatic** [comment]
that would be great if you could take a look on the wrong pdb can you write me an email with you contact, i don't want to make it public:
florijanh [atuz] gmail.com

I removed the assert and added the file again, so far it looks good with windbg

**Comment by elmirjagudin** [comment]
Fixed in commit https://github.com/elmirjagudin/symstore/commit/dad61f7365b2df5d73666832e6dd3e0236380129

I'm planning in including this fix in 0.2.3 release.

**Comment by elmirjagudin** [comment]
Fixed included in 0.2.3 release. Thank you @cinatic for reporting and helping to fix this bug.
